### ISSUE TITLE
Add hindi language localization support for the design patterns

### ISSUE THREAD

**Issue by rishu1601** [iluwatar/java-design-patterns#2121] opened 2022-10-19 07:12 UTC
Add the following README files:
- localization/hi/adapter/README.md
- localization/hi/factory/README.md
- localization/hi/observer/README.md

**Comment by rishu1601** [comment] 2022-10-19 07:13
I nominate myself to work on the issue @iluwatar

**Comment by iluwatar** [comment] 2022-10-19 17:00
Looking forward to the PR @rishu1601

**Comment by rishu1601** [comment] 2022-10-20 03:40
Hey @iluwatar , please review this PR: https://github.com/iluwatar/java-design-patterns/pull/2128

**Comment by Rizwan102003** [comment] 2023-04-17 17:15
Hello,i would like to work on this issue if noone is working on it.

**Comment by Rizwan102003** [comment] 2023-06-10 14:46
Thanks

**Comment by ibrahim89** [comment] 2023-08-13 20:03
Is there any progress on this issue. If no one is working on this can you please assign it to me?

**Comment by ibrahim89** [comment] 2023-08-14 19:22
Thanks @iluwatar. I'll look into this.

**Comment by ibrahim89** [comment] 2023-08-15 09:57
Hi @iluwatar befoe starting actual wok on this hindi translation I wanted to ensure that no other person is working on this. but as I can see there is already one PR  [https://github.com/iluwatar/java-design-patterns/pull/2557](url) is open and @surjendu104 is working on this. let me know what is your opinion on this.

**Comment by iluwatar** [comment] 2023-08-15 18:50
Yes, please collaborate and agree on the parts each of you will translate

**Comment by surjendu104** [comment] 2023-08-16 02:00
Hey @ibrahim89 I have added Hindi translation upto `command` pattern in this or #2557 . You can work on after this. Thanks for collaboration.

**Comment by ibrahim89** [comment] 2023-08-18 20:05
Thans @surjendu104  for the update. I'll be looking into it

**Comment by Parth152004** [comment] 2023-09-30 03:11
I want to work on this issue if no one is working.

**Comment by iluwatar** [comment] 2023-10-01 07:47
Sure @Parth152004, just indicate which parts you are working on

**Comment by tiger3768** [comment] 2023-10-01 20:20
Hey, I would like to work on the observer pattern of the documentation, thank you.

**Comment by KunjMaheshwari** [comment] 2023-10-04 03:45
Please assign this issue to me. I am new to Hacktoberfest. I will resolve this issue in Minimum Time.

**Comment by amanmunjekar** [comment] 2023-10-27 14:29
Please assign this issue to me. I am new to Hacktoberfest. I will resolve this issue in Minimum Time

**Comment by KunjMaheshwari** [comment] 2023-12-27 13:33
ok

**Comment by iluwatar** [comment] 2024-03-31 15:15
Duplicate of #2279

**Closed by iluwatar** 2024-03-31 15:15 UTC
Labels: info: help wanted, info: good first issue, type: feature, epic: documentation
