### ISSUE TITLE
Executable jar problem

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2565] opened 2023-08-20 07:17 UTC
The project includes Maven Assembly plugin to produce executable jars out of all the submodules (individual patterns). However, there currently seems to be a problem with the intended behaviour. 

Steps to reproduce:

1. At the project root build everything, i.e. `mvn clean package -DskipTests=true`
2. Execute one of the produced jars, e.g. `java -jar spatial-partition/target/spatial-partition-1.26.0-SNAPSHOT.jar`

Expected behaviour

- The spatial partition jar is executed and the pattern example runs without problems

Actual behavior

- An error message `no main manifest attribute, in spatial-partition/target/spatial-partition-1.26.0-SNAPSHOT.jar` is printed

**Comment by satyajitbhatt** [comment] 2023-08-21 06:55
Hello @iluwatar Can you give me chance to solve above issue ? If yes then I'm willing to contribute over here and want to help you to solve executable jar problem.

Thank you in advance

**Comment by Sujoydas001** [comment] 2023-09-23 14:13
Can I have a look here ?

**Comment by iluwatar** [comment] 2023-09-24 15:19
@satyajitbhatt are you working on it?

**Comment by satyajitbhatt** [comment] 2023-09-24 16:23
No, I am not.

**Comment by Navneetsinghnegi** [comment] 2023-09-27 06:08
@iluwatar  want to look into the issue and fix it

**Comment by Navneetsinghnegi** [comment] 2023-09-27 06:09
@iluwatar  I want to go through the issue and work upon it

**Comment by BrijeshPatra** [comment] 2023-09-29 10:11
Hi @iluwatar here we have 2 approaches to solve this bug
a) add the name of main class to the jar file
b) create the jar file as an executable jar

**Comment by BrijeshPatra** [comment] 2023-09-29 10:38
I am trying hard to contribute but getting an error *Unable to access jarfile spatial-partition/target/spatial-partition-1.26.0-SNAPSHOT.jar*. It would be helpful if you review it once and suggest me something better @iluwatar

**Comment by BrijeshPatra** [comment] 2023-09-29 10:41
<img width="766" alt="Bug" src="https://github.com/iluwatar/java-design-patterns/assets/93272856/d1c20f36-c6cf-4dae-af5a-ed1fea528729">

**Comment by iluwatar** [comment] 2023-10-01 07:44
Assigned to @Navneetsinghnegi

**Comment by Aniket-kumar404** [comment] 2023-10-01 21:22
I would Like to work on this issue.

**Comment by emcconnell27** [comment] 2024-07-03 07:51
Hi @iluwatar, could please have a go at solving this issue?

**Comment by apophizzz** [comment] 2024-10-07 22:17
Hi @iluwatar, I think I actually found a tiny configuration fix for the assembly plugin that produces a single fat JAR - e.g. `proxy-1.26.0-SNAPSHOT.jar` which successfully executes:

```bash
$ cd proxy/
$ mvn clean package -DskipTests=true 
$ ls -al target/
-rw-r--r--   1 patrick  staff  958950 Oct  8 00:12 proxy-1.26.0-SNAPSHOT.jar
...
$ java -jar target/proxy-1.26.0-SNAPSHOT.jar
00:12:39.160 [main] INFO com.iluwatar.proxy.IvoryTower -- Red wizard enters the tower.
00:12:39.162 [main] INFO com.iluwatar.proxy.IvoryTower -- White wizard enters the tower.
00:12:39.163 [main] INFO com.iluwatar.proxy.IvoryTower -- Black wizard enters the tower.
00:12:39.163 [main] INFO com.iluwatar.proxy.WizardTowerProxy -- Green wizard is not allowed to enter!
00:12:39.163 [main] INFO com.iluwatar.proxy.WizardTowerProxy -- Brown wizard is not allowed to enter!
```

Feel free to assign the issue to me and I'll submit a PR. Thx!

**Comment by ananyadhagat** [comment] 2024-10-17 12:46
Hey I am working on this issue @iluwatar

**Comment by Soumayadip937** [comment] 2024-10-19 21:42
@iluwatar I am new to open source contribution, could you please help me to get started on this issue?

**Comment by yuvraj-kumar-dev** [comment] 2024-10-20 11:50
Hi @iluwatar,
I'd love to tackle the Maven Assembly plugin issue. Could you please assign this task to me?
Thank you!

**Comment by abhi8f** [comment] 2024-10-23 13:59
Hi @iluwatar 
![image](https://github.com/user-attachments/assets/1c26f4bc-9108-4d04-b2f8-2d06ba00bf3c)
there is two jar files spatial-partition-1.26.0-SNAPSHOT.jar and spatial-partition.jar
is 2 jar files intended behavior ? if no i have soultion

![image](https://github.com/user-attachments/assets/8c1e430b-2404-4aa7-9b2b-703781be93a8)

if only one jar file is required, putting filename in maven assembly plugin works 
i can do this and raise a pull request

**Closed** 2024-11-15 19:04 UTC
Labels: type: bug, info: good first issue, epic: build issue
