### ISSUE TITLE
pdf document

### ISSUE THREAD

**Issue by carousel** [iluwatar/java-design-patterns#1691] opened 2021-03-25 13:48 UTC
Hello, 

I have merged all README.md files into one .pdf document. It may be useful to have all theories about patterns in one place, instead of jumping from folder to folder. If someone finds it useful, I will be happy :) 

It can be found here:

[patterns.pdf](https://github.com/carousel/java-design-patterns/blob/master/patterns.pdf)

PS it is not perfect formatted but it will do the job of reading.

**Comment by ohbus** [comment] 2021-03-25 14:16
Hi @carousel Thank for the collaboration 🎉  and checking out this project! We are really glad to have you here.

Thank you so much for putting the effort 👏🏻 of collating the whole project into one single PDF. It was a daunting task indeed which I agree.

Though it is good for a quick reference you can checkout our ➡️ [website](https://java-design-patterns.com 
) where we maintain all these design patterns at
### 🌟  https://java-design-patterns.com 

> You can also check out our [**Wiki**](https://github.com/iluwatar/java-design-patterns/wiki) section for contribution guidelines from 📄  [here](https://github.com/iluwatar/java-design-patterns/wiki). 

***

We are building a 🆕 modified version of the website here https://github.com/iluwatar/java-design-patterns-vuepress-web
You can also get a sneak peek 👀  at what is cooking from [here](https://jdp-vue.netlify.app/).

***

If you want to 🔍  explore further to this PDF topic we might need to get it automated for building a PDF version for each pattern. I can do the work of publishing you. 
But I do not see the need of maintaining another binary file unless we have some solid reasons to do so. Do you mind if you can discuss and share some advantages and use cases for this ❓ We will be glad to hear them.  🤝

**Comment by iluwatar** [comment] 2021-03-28 07:13
Thanks @carousel for putting effort into this. I like the idea but would like to take it a couple of steps further. What if the website could dynamically build this presentation out of all the patterns that are available?

**Comment by IAmPramod** [comment] 2021-09-03 15:59
@iluwatar Would it make sense to provide the functionality to download the content of specific patterns in pdf?

**Comment by iluwatar** [comment] 2021-09-09 15:04
Yes, I think that story fits the same epic as well

**Comment by yashdeshmukh007** [comment] 2021-09-24 14:35
I am Confused What to do in this Task If you want to print the pattern in the pdf then i am ready to print the pattern on the pdf

**Comment by yashdeshmukh007** [comment] 2021-09-24 14:35
I am Confused What to do in this Task If you want to print the pattern in the pdf then i am ready to print the pattern on the pdf

**Comment by ohbus** [comment] 2021-09-28 16:14
This should be a Dynamic On-Demand feature if we want to implement it.

**Comment by iluwatar** [comment] 2021-09-28 18:50
This task is now a duplicate of https://github.com/iluwatar/java-design-patterns-vuepress-web/issues/7 and can be closed

**Closed by iluwatar** 2021-09-28 18:50 UTC
Labels: epic: web site, type: feature, type: docs
