### ISSUE TITLE
Setting up CircleCI workflow to allow contributors run sonarcloud from a forked Repo

### ISSUE THREAD

**Issue by joseosuna-engineer** [iluwatar/java-design-patterns#1697] opened 2021-04-07 21:26 UTC
@iluwatar @ohbus 
I have added this project to my own CircleCI and SonarCloud accounts to run SonarCloud before create a pull request.

**My accounts:**
![image](https://user-images.githubusercontent.com/2281302/113358032-669e9100-931b-11eb-8d05-5b3dbf3c0b7b.png)

I **changed two config files**, :scream: **.circleci/config.yml** and **pom.xml** (my fork, another branch) 
I'm sure @iluwatar @ohbus that we can find a better approach using environment vars or some characteristic of 
CircleCI 2.1 [Youtube](https://www.youtube.com/watch?v=etXD9sCFxIU)

My strategy is: 
- to use this branch **A** only in my fork.
- to create another branch **B** to commit my code.
- to merge **B** to **A** and run CircleCI + SonarCloud
- when code is okay create a pull request from **B** (that has original config files) to master

![image](https://user-images.githubusercontent.com/2281302/113358878-fbee5500-931c-11eb-8cbf-caeeca0a0d52.png)

![image](https://user-images.githubusercontent.com/2281302/113358940-1c1e1400-931d-11eb-940f-a744b88f4a75.png)

**Comment by iluwatar** [comment] 2021-04-18 09:46
I think the aim of this issue is to create instructions on how to run the Sonar analysis for your own changes. We could add the documentation to our [Wiki](https://github.com/iluwatar/java-design-patterns/wiki).

**Comment by ohbus** [comment] 2021-04-19 11:45
I do not see any use case for having your own sonarcloud for the same project as it will create conflict while creating PRs to fix them in upstream.

**Comment by iluwatar** [comment] 2021-04-25 13:13
I guess the question is how could one verify that the changes really fix a Sonar issue in the `master` before the changes are merged.

**Comment by joseosuna-engineer** [comment] 2021-05-02 14:36
> 
> 
> I do not see any use case for having your own sonarcloud for the same project as it will create conflict while creating PRs to fix them in upstream.

@ohbus as the images above show, in order to use my own sonarcloud I need to modify pom.xml.
if I do that in my own branch (fork), when I ask a PR that pom.xml commit is going to be included
I could ignore pom.xml in my commits, but what happen when my changes need to add a dependency?

**Comment by joseosuna-engineer** [comment] 2021-05-02 14:54
> 
> 
> I guess the question is how could one verify that the changes really fix a Sonar issue in the `master` before the changes are merged.

@iluwatar yes, that is the question.
My strategy is not easy, it is to use your own sonarqube and 2 branches to avoid merging pom.xml changes
A easier strategy could be to use the project sonarqube and as you suggested before: we need to add some entry or more explanation in the wiki pages [11.-Static-analysis](https://github.com/iluwatar/java-design-patterns/wiki/11.-Static-analysis)

![image](https://user-images.githubusercontent.com/2281302/116817301-9b2c8500-ab33-11eb-84c0-0b10c601acde.png)

We have scan for master and PR
We need scan for branches too

Let me change the name of this is issue from "Setting up CircleCI workflow to allow contributors run their own CircleCI and SonarCloud" to "Setting up CircleCI workflow to allow contributors run sonarcloud from a forked Repo"

**Comment by brian474** [comment] 2021-05-18 09:26
Duplicate of #

**Comment by ohbus** [comment] 2021-05-19 17:58
> > I guess the question is how could one verify that the changes really fix a Sonar issue in the `master` before the changes are merged.
> 
> @iluwatar yes, that is the question.
> My strategy is not easy, it is to use your own sonarqube and 2 branches to avoid merging pom.xml changes
> A easier strategy could be to use the project sonarqube and as you suggested before: we need to add some entry or more explanation in the wiki pages [11.-Static-analysis](https://github.com/iluwatar/java-design-patterns/wiki/11.-Static-analysis)
> 
> ![image](https://user-images.githubusercontent.com/2281302/116817301-9b2c8500-ab33-11eb-84c0-0b10c601acde.png)
> 
> We have scan for master and PR
> We need scan for branches too
> 
> Let me change the name of this is issue from "Setting up CircleCI workflow to allow contributors run their own CircleCI and SonarCloud" to "Setting up CircleCI workflow to allow contributors run sonarcloud from a forked Repo"

What you are suggesting that you want to add a job for SonarCloud analysis job using any CI platform _(CircleCI in your case)_ is that it needs an upgraded plan of SonarCloud for this operation.

And this is where you are deferring from the actual goal that you intended to use this setup for was to clear and resolve already existing issues. This would be an interesting metric to see where we can see on a PR if some existing issues are being resolved or not when new changes are pushed.

Also, make a note if that while updating the pom file for making your sonar configurations with your own fork will you be able to make a PR from that branch or not. And I have a proposed solution for this as well where you will be tracking the resolved issues from your own sonar repositories and then cherry-pick those commits to a new branch for which you will be making the PR against our master branch in this repository. Please mention if you have any other plans than this workflow. I know it is a bit tedious.

**Comment by joseosuna-engineer** [comment] 2021-06-07 15:23
@ohbus thank you for your comment. Let me explain my concerns. 

When I tried to solve some issues I wanted to know what was my daily progress. Did I fix 1, 2 or more issues? What I did fix the issues? What was my progress today? Because fixing that issues is a big task. It requires more than a couple of hours.

So I looked at the project's sonarqube page and it only is called if you ask for a PR, but you only would ask for a PR if the whole task is finished. 

So how do you how your daily progress before all the issues are fixed?

My first approach was adding my own sonarqube account, but we are in a community, if I do that what is going on with other colaborators? They must have their own sonarcloud accounts? What if sonarqube metrics are different? 

So a better approach is to use one centralized sonarcloud account: the project one.

How we can do that without asking for a PR?

- travis-ci settings?
- sonarcloud settings?

It would be great if that solution is a fixed automated and transparent setting. 

We don't use branching by stage like: develop, release and master, we have master and forked branches. So the solution could be some setting in sonarcloud or travis or both that let you to run your own fork branch, and you can see your stads.

**Comment by joseosuna-engineer** [comment] 2021-06-07 15:27
@ohbus I use Travis, I have opened a Circle-CI account because of this project. So I what I mean was Circle-Ci

**Comment by ohbus** [comment] 2021-06-07 16:31
> @ohbus thank you for your comment. Let me explain my concerns.
> 
> When I tried to solve some issues I wanted to know what was my daily progress. Did I fix 1, 2 or more issues? What I did fix the issues? What was my progress today? Because fixing that issues is a big task. It requires more than a couple of hours.
> 
> So I looked at the project's sonarqube page and it only is called if you ask for a PR, but you only would ask for a PR if the whole task is finished.
> 
> So how do you how your daily progress before all the issues are fixed?
> 
> My first approach was adding my own sonarqube account, but we are in a community, if I do that what is going on with other colaborators? They must have their own sonarcloud accounts? What if sonarqube metrics are different?
> 
> So a better approach is to use one centralized sonarcloud account: the project one.
> 
> How we can do that without asking for a PR?
> 
> * travis-ci settings?
> * sonarcloud settings?
> 
> It would be great if that solution is a fixed automated and transparent setting.
> 
> We don't use branching by stage like: develop, release and master, we have master and forked branches. So the solution could be some setting in sonarcloud or travis or both that let you to run your own fork branch, and you can see your stads.

I can totally understand your concern over here. But as mentioned you may need to cherry-pick commits before making the PR.

What we all want is, to get a metric if a submitted PR is resolving an existing Sonar issue or not.

**Closed** 2022-12-29 11:17 UTC
Labels: info: help wanted, epic: build issue, epic: documentation
