### ISSUE TITLE
Hibernate of current version doesn't match h2

### ISSUE THREAD

**Issue by castleKing1997** [iluwatar/java-design-patterns#1929] opened 2021-12-13 02:21 UTC
I use hibernate and h2 inherited from the parent pom.xml whose version are `5.2.18.Final`.
But I find the `org.hibernate.dialect.H2Dialect` extends from `org.hibernate.dialect.Dialect` didn't override method `getCurrentSchemaCommand`, which leeds it reture `null`.
Then I received an exception when I use hibernate to connect h2database:
```bash
org.hibernate.HibernateException: Use of DefaultSchemaNameResolver requires Dialect to provide the proper SQL statement/command but provided Dialect [org.hibernate.dialect.H2Dialect] did not return anything from Dialect#getCurrentSchemaCommand
	at org.hibernate.engine.jdbc.env.internal.DefaultSchemaNameResolver$SchemaNameResolverFallbackDelegate.resolveSchemaName(DefaultSchemaNameResolver.java:100)
	at org.hibernate.engine.jdbc.env.internal.DefaultSchemaNameResolver.resolveSchemaName(DefaultSchemaNameResolver.java:76)
......
```
It occurs becaus 
```bash
public String resolveSchemaName(Connection connection, Dialect dialect) throws SQLException {
	final String command = dialect.getCurrentSchemaCommand();
	if ( command == null ) {
		throw new HibernateException(
				"Use of DefaultSchemaNameResolver requires Dialect to provide the " +
						"proper SQL statement/command but provided Dialect [" +
						dialect.getClass().getName() + "] did not return anything " +
						"from Dialect#getCurrentSchemaCommand"
		);
	}
        ......
}
```
but the code can run successfully for some reasons. you can reproduce this case in my [code](https://github.com/castleKing1997/java-design-patterns/tree/master/metadata-mapping)
Is is necessary to fix it?
Maybe a new version of hibernate?

**Comment by Linly1080** [comment] 2022-04-23 16:29
Hi, I'd like to work on this issue. Could it be assigned to me if still available?

**Comment by iluwatar** [comment] 2022-09-10 12:24
Thanks @Linly1080, please go ahead

**Comment by Linly1080** [comment] 2022-09-17 03:56
@iluwatar sorry, I have no time to do the work now.

**Comment by robertvolkmann** [comment] 2022-10-24 16:52
The issue is still present in 5.4.24. To verify run `com.iluwatar.metamapping.AppTest` and look for
`
org.hibernate.HibernateException: Use of DefaultSchemaNameResolver requires Dialect to provide the proper SQL statement/command but provided Dialect [org.hibernate.dialect.H2Dialect] did not return anything from Dialect#getCurrentSchemaCommand
	at org.hibernate.engine.jdbc.env.internal.DefaultSchemaNameResolver$SchemaNameResolverFallbackDelegate.resolveSchemaName(DefaultSchemaNameResolver.java:100)
	at org.hibernate.engine.jdbc.env.internal.DefaultSchemaNameResolver.resolveSchemaName(DefaultSchemaNameResolver.java:76)
`

**Comment by robertvolkmann** [comment] 2022-10-24 17:57
We would get rid of the HibernateException by implementing a custom SchemaNameResolver
```
By default, Hibernate uses the [org.hibernate.dialect.Dialect#getSchemaNameResolver](https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/dialect/Dialect.html#getSchemaNameResolver--). You can customize how the schema name is resolved by providing a custom implementation of the [SchemaNameResolver](https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/engine/jdbc/env/spi/SchemaNameResolver.html) interface.
```

https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#_table_qualifying_options

**Comment by robertvolkmann** [comment] 2022-10-24 18:05
My advice is to close this issue because it is only some strange error message from some weird internal Hibernate implementation. The same message will also be shown for all MySQLDialects because MySQL doesn't support schemas nativley like PostgreSQL.

**Closed** 2022-10-30 15:40 UTC
Labels: type: bug, info: help wanted, epic: dependencies, priority: normal
