### ISSUE TITLE
CircuitBreaker pattern. 

### ISSUE THREAD

**Issue by rinormaloku** [iluwatar/java-design-patterns#542] opened 2017-02-22 03:28 UTC
http://www.hascode.com/2017/02/resilient-architecture-circuit-breakers-for-java-hystrix-vert-x-javaslang-and-failsafe-examples/

**Comment by iluwatar** [comment] 2017-02-22 05:00
Duplicate of https://github.com/iluwatar/java-design-patterns/issues/413

**Closed by iluwatar** 2017-02-22 05:00 UTC
Labels: duplicate, won't fix
