### ISSUE TITLE
Loan pattern

### ISSUE THREAD

**Issue by javatlacati** [iluwatar/java-design-patterns#1843] opened 2021-10-07 17:32 UTC
Reference: https://www.javacodegeeks.com/2013/01/loan-pattern-in-java-a-k-a-lender-lendee-pattern.html

**Comment by iluwatar** [comment] 2021-10-08 17:58
You are free to take a shot @Pikmin1211

**Comment by iluwatar** [comment] 2021-11-28 07:27
@Pikmin1211 are you working on this?

**Comment by Surya-Prakash-Reddy** [comment] 2022-01-08 12:44
@iluwatar If no one is working on this, can you assign this to me?

**Comment by iluwatar** [comment] 2022-01-08 18:40
Yes, assigned to @Surya-Prakash-Reddy

**Comment by iluwatar** [comment] 2022-09-21 17:30
@Surya-Prakash-Reddy are you working on this?

**Comment by u7341910** [comment] 2022-10-03 23:28
I am working on this. Could you assign this to me?

**Comment by iluwatar** [comment] 2022-10-04 05:21
Ok @u7341910

**Comment by sabalanga06** [comment] 2022-10-19 16:31
hello sir ,can you assign this issue to me ?

**Comment by iluwatar** [comment] 2022-10-19 17:04
It's already under construction @sabalanga06, so please find something else

**Comment by iluwatar** [comment] 2022-12-03 17:02
The issue is free, if anyone wants to work on it

**Comment by Shelly-Shih** [comment] 2023-10-04 00:24
@iluwatar I am happy to do this issue, can you assign it to me?

**Comment by Shelly-Shih** [comment] 2023-10-18 00:51
Sorry, I clicked the wrong button. Can you assign this issue to me? thanks

**Closed** 2024-05-31 19:51 UTC
Labels: info: help wanted, epic: pattern, type: feature
