### ISSUE TITLE
add Filter pattern

### ISSUE THREAD

**Issue by MohammadRehanPatel** [iluwatar/java-design-patterns#2062] opened 2022-10-07 12:31 UTC
please give PR with Hacktoberfest badge

**Comment by skullkim** [comment] 2022-10-08 05:27
I like to work on this issue.

**Comment by MohammadRehanPatel** [comment] 2022-10-08 07:24
I already have code for that woth a good example

**Comment by iluwatar** [comment] 2022-10-08 10:31
Ok, assigned to @MohammadRehanPatel. Can you also list an authoritative source for the pattern?

**Comment by MohammadRehanPatel** [comment] 2022-10-08 12:20
done

**Comment by MohammadRehanPatel** [comment] 2022-10-10 12:28
please add hacktoberfest tag

**Comment by iluwatar** [comment] 2022-10-10 15:51
The repository has the hacktoberfest tag. I believe it's enough for the contributors to submit any pull request, and once it gets approved, the hactoberfest PR count is increased.

**Comment by MohammadRehanPatel** [comment] 2022-10-11 08:28
I Learn this pattern during a course from udamy

**Comment by aniketkumar-1907** [comment] 2022-10-12 10:01
Can I work on this issue @skullkim.

**Comment by drashan14** [comment] 2022-10-13 02:43
Sir i would like to do work on this topic could you assign me this issue.

**Comment by Zaid-Parkar** [comment] 2022-10-16 06:14
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by ArchontisKostis** [comment] 2022-10-17 09:19
is anyone assigned to this issue? Iwould like to work on it

**Comment by MohammadRehanPatel** [comment] 2022-10-17 11:39
I Already Done it

**Comment by iluwatar** [comment] 2022-12-03 16:49
The issue is free, if anyone wants to take a shot

**Comment by lollanlollan** [comment] 2023-02-23 12:30
We're a group of students that would like to work on this issue.

**Comment by iluwatar** [comment] 2023-03-03 15:04
Go ahead @lollanlollan

**Comment by Pratik-kp** [comment] 2023-07-09 15:34
Is this issue still open @iluwatar , I would like to take a shot

**Comment by sugan0tech** [comment] 2023-10-03 14:20
@Pratik-kp  can I know the status of your progress?

**Closed** 2024-05-31 19:52 UTC
Labels: info: help wanted, epic: pattern, type: feature
