### ISSUE TITLE
Aggregator Microservices tests broken

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1473] opened 2020-08-03 17:37 UTC
Running the `AggregatorTest` produces

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/home/ilkka/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by amit1307** [comment] 2020-08-09 14:03
I have bit of an idea about this issue:
1. Tests are running fine it's just a warning.
2. The warning is caused by an older version of mockito, if we see the warning stack it shows 1.10 which is very old.
3. Enforcing any mockito version >= 2.23.4 should fix this issue.
4. More info https://github.com/mockito/mockito-cglib/issues/1

Happy to fix it if you would like it assign to me.

**Comment by iluwatar** [comment] 2020-08-09 14:58
Many thanks @amit1307 for looking into this. Yes, I agree it seems to be just a warning. I created a new ticket about upgrading mockito version, see https://github.com/iluwatar/java-design-patterns/issues/1486. Please comment there if you want to work on it.

**Closed** 2020-08-09 14:59 UTC
Labels: epic:build issue, priority:normal, resolution:fixed, status:under construction, type:bug
